import Foundation

/// UTIs that decide whether a pasteboard change is ours, someone's secret, or ordinary content.
public enum PasteboardConventions {
    /// Set on every write ClipRoid makes, carrying the source clip's UUID.
    ///
    /// This is the backstop behind the change-count handshake. If a tick somehow sees a bumped
    /// count that we actually own — a third-party app wrote between our two writes, or a crash
    /// lost the counter — the poller finds this marker and promotes the existing clip instead of
    /// inserting a duplicate.
    public static let originType = "dev.philtronic.ClipRoid.origin"

    /// Community conventions from nspasteboard.org. Widely honoured by password managers and
    /// clipboard tools; respecting them is the difference between a clipboard manager that can be
    /// trusted with a password manager installed and one that cannot.
    public static let transientType = "org.nspasteboard.TransientType"
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    /// Universal Clipboard. Reading one of these forces a network fetch from the paired device,
    /// so they are deferred until the user actually looks at the clip.
    public static let remoteClipboardType = "com.apple.is-remote-clipboard"

    /// Content ClipRoid must not persist at all.
    public static func shouldSkipCapture(declaredTypes: [String]) -> Bool {
        let skip: Set<String> = [transientType, concealedType, autoGeneratedType]
        return declaredTypes.contains { skip.contains($0) }
    }

    /// A concealed item is a password manager telling us, explicitly, that this is a secret.
    /// The most reliable sensitivity signal available — better than any regex.
    public static func isConcealed(declaredTypes: [String]) -> Bool {
        declaredTypes.contains(concealedType)
    }
}
