#!/usr/bin/env bash
#
# Assembles ClipRoid.app from the SwiftPM executable.
#
# SwiftPM produces a bare executable. macOS needs a bundle for an app icon, a bundle identifier
# (which TCC grants, login items and notifications are all keyed on), and a code signature.
#
#   Scripts/bundle.sh [debug|release]       # local build, self-signed
#   Scripts/bundle.sh release --notarize    # Developer ID, hardened runtime, notarized, stapled
#
set -euo pipefail

CONFIGURATION="release"
NOTARIZE=0
for arg in "$@"; do
    case "$arg" in
        debug|release) CONFIGURATION="$arg" ;;
        --notarize) NOTARIZE=1 ;;
        *) echo "error: unknown argument '$arg'" >&2; exit 2 ;;
    esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="ClipRoid"

# Fixed from the first build and never changed. Every Accessibility and Screen Recording grant the
# app is given is keyed on this string; changing it silently revokes all of them.
BUNDLE_ID="dev.philtronic.ClipRoid"
MIN_MACOS="26.0"
FALLBACK_IDENTITY="ClipRoid Development"

# Signing identity. Prefer an Apple Development certificate over the local self-signed one.
#
# This is not cosmetic. A self-signed certificate has no TeamIdentifier, and without one TCC pins
# Accessibility and Screen Recording grants to the cdhash — so every rebuild revokes them, and the
# resulting "paste silently does nothing" is indistinguishable from a bug in the paste path.
# An Apple Development certificate carries a TeamIdentifier and an Apple-anchored designated
# requirement, which is what lets a grant survive a rebuild. See Docs/spikes.md, S3.
resolve_identity() {
    local apple_dev
    apple_dev="$(security find-identity -v -p codesigning \
        | sed -n 's/.*"\(Apple Development: [^"]*\)".*/\1/p' | head -1)"
    if [[ -n "$apple_dev" ]]; then
        printf '%s' "$apple_dev"
        return 0
    fi
    if security find-identity -v -p codesigning | grep -q "$FALLBACK_IDENTITY"; then
        echo "warning: no Apple Development certificate found; falling back to" >&2
        echo "         \"$FALLBACK_IDENTITY\". Signing works, but TCC grants will be" >&2
        echo "         revoked on every rebuild (Docs/spikes.md, S3)." >&2
        printf '%s' "$FALLBACK_IDENTITY"
        return 0
    fi
    return 1
}


VERSION="$(git -C "$ROOT" describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")"
VERSION="${VERSION#v}"
BUILD_NUMBER="$(git -C "$ROOT" rev-list --count HEAD 2>/dev/null || echo "1")"

echo "Building $APP_NAME $VERSION ($BUILD_NUMBER) in $CONFIGURATION..."
swift build --package-path "$ROOT" -c "$CONFIGURATION"

BIN_DIR="$(swift build --package-path "$ROOT" -c "$CONFIGURATION" --show-bin-path)"
EXECUTABLE="$BIN_DIR/ClipRoidApp"
if [[ ! -x "$EXECUTABLE" ]]; then
    echo "error: no executable at $EXECUTABLE" >&2
    exit 1
fi

# A stable output path, deliberately. TCC keys grants on the bundle path as well as its signature,
# so building into a mktemp directory would hand back a fresh set of permission prompts each time.
APP="$ROOT/.build/$APP_NAME.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$EXECUTABLE" "$APP/Contents/MacOS/$APP_NAME"

# Every usage-description string below is commented with what breaks without it, following the
# style of ~/projects/aug-wifi/App/Info.plist.
#
# Note what is NOT here: there is no usage-description key for Accessibility or Screen Recording.
# Those prompts are generated by the system and cannot be customised; inventing
# NSAccessibilityUsageDescription does nothing at all. Explaining them is the onboarding flow's job.
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleVersion</key>
    <string>$BUILD_NUMBER</string>
    <key>LSMinimumSystemVersion</key>
    <string>$MIN_MACOS</string>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.productivity</string>
    <key>NSPrincipalClass</key>
    <string>NSApplication</string>
    <key>NSHighResolutionCapable</key>
    <true/>

    <!-- Reading a file clip's bytes to build its thumbnail crosses these TCC gates even in an
         unsandboxed app. Without a string the prompt renders blank and looks broken. -->
    <key>NSDesktopFolderUsageDescription</key>
    <string>ClipRoid reads files you copy so it can show you a preview of them.</string>
    <key>NSDocumentsFolderUsageDescription</key>
    <string>ClipRoid reads files you copy so it can show you a preview of them.</string>
    <key>NSDownloadsFolderUsageDescription</key>
    <string>ClipRoid reads files you copy so it can show you a preview of them.</string>

    <!-- App Nap would otherwise throttle the pasteboard poller in the background, which shows up
         as clips silently going missing. The runtime assertion in AppEnvironment is the other half
         of this; both are needed. -->
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSSupportsSuddenTermination</key>
    <false/>
</dict>
</plist>
PLIST

if [[ "$NOTARIZE" -eq 1 ]]; then
    : "${DEVELOPER_ID:?set DEVELOPER_ID to your 'Developer ID Application: ...' identity}"
    : "${NOTARY_PROFILE:?set NOTARY_PROFILE to a notarytool --keychain-profile name}"

    echo "Signing with Developer ID and hardened runtime..."
    codesign --force --options runtime --timestamp \
        --sign "$DEVELOPER_ID" "$APP"

    ZIP="$ROOT/.build/$APP_NAME-$VERSION.zip"
    ditto -c -k --keepParent "$APP" "$ZIP"
    echo "Submitting to notarytool (this waits for the result)..."
    xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait
    xcrun stapler staple "$APP"
    rm -f "$ZIP"
    echo "Notarized and stapled."
else
    # Refuse to fall back to ad-hoc signing silently. Ad-hoc mints a new identity per build, which
    # revokes the app's Accessibility and Screen Recording grants every single time — and the
    # resulting misbehaviour is indistinguishable from a bug in the paste path.
    if ! SIGN_IDENTITY="$(resolve_identity)"; then
        echo "error: no usable code-signing identity." >&2
        echo "       Either sign in to an Apple ID in Xcode > Settings > Accounts (preferred)," >&2
        echo "       or run Scripts/create-signing-identity.sh." >&2
        echo "       Signing ad-hoc instead would revoke the app's TCC grants on every rebuild," >&2
        echo "       so this script will not do it for you." >&2
        exit 1
    fi
    echo "Signing with: $SIGN_IDENTITY"
    codesign --force --sign "$SIGN_IDENTITY" "$APP"
fi

codesign --verify --strict --deep "$APP"
echo "Built $APP"
